import numpy as np
a=np.random.randint(0,100,5)
print(a)
np.random.seed(50)
b=np.random.rand(5)
c=np.random.randint(1,100,5)
print(b)
print(c)
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
euclidean_distance=np.sqrt(np.sum(arr-arr1)**2)
print(euclidean_distance)
manhattan_distance=np.sum(np.abs(arr-arr1))
print(manhattan_distance)